# This workflow will do a clean install of node dependencies, run JS and Typescript tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: [push, pull_request]

jobs:
  render-html:
    name: react-native-render-html
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Cache .dts
      id: cache-dts
      uses: actions/cache@v2
      with:
        path: .dts
        key: ${{ runner.os }}-dts
    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: lts/*
        cache: 'yarn'
    - run: yarn install --immutable
    - run: yarn workspace react-native-render-html test:ts
      name: Typescript Tests
    - run: yarn workspace react-native-render-html test:jest --coverage
      name: Jest Tests
    - run: yarn workspace react-native-render-html test:lint
      name: Linting Tests
    - run: yarn workspace react-native-render-html build
      name: Build
    - run: yarn build:tools
      name: Build Tooling Libraries
    - uses: codecov/codecov-action@v2
      with:
        file: ./packages/render-html/coverage/clover.xml # optional
        fail_ci_if_error: true # optional (default = false)
  website:
    name: Documentation Website
    needs: render-html
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: lts/*
        cache: 'yarn'
    - run: yarn install --immutable
    - run: yarn workspace react-native-render-html build
      name: Build sources
    - run: yarn process-svg-assets
      name: Process SVG assets
    - run: yarn build:tools
      name: Build Tooling Libraries
    - run: yarn build:docs
      name: Build documentation
    - run: yarn website build
      name: Build website

  discovery:
    name: Discovery App
    needs: render-html
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: lts/*
        cache: 'yarn'
    - name: Setup Expo and EAS
      uses: expo/expo-github-action@v7
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    - run: yarn install --immutable
    - run: yarn workspace react-native-render-html build
      name: Build sources
    - run: yarn process-svg-assets
      name: Process SVG assets
    - run: yarn build:tools
      name: Build Tooling Libraries
    - run: yarn build:docs
      name: Build documentation
    - run: yarn discovery test:ts
      name: Discovery TS
    - run: yarn discovery test:lint
      name: Discovery Lint
    - run: yarn discovery eas build --platform android --non-interactive
      name: Discovery Build Android